const presetUsers = [ 
   { username: "test", email: "test@gmail.com", bio: "account for testing the database", password: "123"  },
   { username: "test1", email: "test1@gmail.com", bio: "account for testing the database", password: "123"  },
   { username: "test2", email: "test2@gmail.com", bio: "account for testing the database", password: "123"  },
   { username: "test3", email: "test3@gmail.com", bio: "account for testing the database", password: "123"  },
   { username: "test4", email: "test4@gmail.com", bio: "account for testing the database", password: "123"  },
   { username: "test5", email: "test5@gmail.com", bio: "account for testing the database", password: "123"  },
   { username: "test6", email: "test6@gmail.com", bio: "account for testing the database", password: "123"  },
   { username: "test7", email: "test7@gmail.com", bio: "account for testing the database", password: "123"  },
   { username: "test8", email: "test8@gmail.com", bio: "account for testing the database", password: "123"  },
   { username: "test9", email: "test9@gmail.com", bio: "account for testing the database", password: "123"  },
   { username: "test0", email: "test0@gmail.com", bio: "account for testing the database", password: "123"  },
   { username: "mackenzieNeill", email: "mackenzie@gmail.com", bio: "default account for mackenzie", password: "123"  },
   { username: "connorPink", email: "connor@gmail.com", bio: "default account for connor", password: "123"  },
   { username: "alexSmith", email: "alex@gmail.com", bio: "default account for alex", password: "123" },
   { username: "sarahJohnson", email: "sarah@gmail.com", bio: "default account for sarah", password: "123" },
   { username: "michaelBrown", email: "michael@gmail.com", bio: "default account for michael", password: "123" },
   { username: "emilyDavis", email: "emily@gmail.com", bio: "default account for emily", password: "123" },
   { username: "davidMartinez", email: "david@gmail.com", bio: "default account for david", password: "123" },
   { username: "jamesGarcia", email: "james@gmail.com", bio: "default account for james", password: "123" },
   { username: "isabellaMiller", email: "isabella@gmail.com", bio: "default account for isabella", password: "123" },
   { username: "ethanLopez", email: "ethan@gmail.com", bio: "default account for ethan", password: "123" },
   { username: "oliviaWilson", email: "olivia@gmail.com", bio: "default account for olivia", password: "123" },
   { username: "danielAnderson", email: "daniel@gmail.com", bio: "default account for daniel", password: "123" },
   { username: "avaThomas", email: "ava@gmail.com", bio: "default account for ava", password: "123" },
   { username: "lucasTaylor", email: "lucas@gmail.com", bio: "default account for lucas", password: "123" },
   { username: "miaMoore", email: "mia@gmail.com", bio: "default account for mia", password: "123" },
   { username: "benjaminHernandez", email: "benjamin@gmail.com", bio: "default account for benjamin", password: "123" },
   { username: "harperClark", email: "harper@gmail.com", bio: "default account for harper", password: "123" },
   { username: "jacksonLee", email: "jackson@gmail.com", bio: "default account for jackson", password: "123" },
   { username: "sophiaWalker", email: "sophia@gmail.com", bio: "default account for sophia", password: "123" },
   { username: "aidenHall", email: "aiden@gmail.com", bio: "default account for aiden", password: "123" },
   { username: "ellaAllen", email: "ella@gmail.com", bio: "default account for ella", password: "123" },
   { username: "loganYoung", email: "logan@gmail.com", bio: "default account for logan", password: "123" },
   { username: "scarlettKing", email: "scarlett@gmail.com", bio: "default account for scarlett", password: "123" },
   { username: "jacobWright", email: "jacob@gmail.com", bio: "default account for jacob", password: "123" },
   { username: "graceScott", email: "grace@gmail.com", bio: "default account for grace", password: "123" },
   { username: "liamGreen", email: "liam@gmail.com", bio: "default account for liam", password: "123" },
   { username: "zacharyAdams", email: "zachary@gmail.com", bio: "default account for zachary", password: "123" },
   { username: "chloeBaker", email: "chloe@gmail.com", bio: "default account for chloe", password: "123" },
   { username: "noahNelson", email: "noah@gmail.com", bio: "default account for noah", password: "123" },
   { username: "averyCarter", email: "avery@gmail.com", bio: "default account for avery", password: "123" },
   { username: "elijahMitchell", email: "elijah@gmail.com", bio: "default account for elijah", password: "123" },
   { username: "victoriaPerez", email: "victoria@gmail.com", bio: "default account for victoria", password: "123" },
   { username: "oliverRoberts", email: "oliver@gmail.com", bio: "default account for oliver", password: "123" },
   { username: "aubreyFoster", email: "aubrey@gmail.com", bio: "default account for aubrey", password: "123" },
   { username: "masonGonzalez", email: "manson@gmail.com", bio: "default account for mason", password: "123" },
]

module.exports = presetUsers;